-- AlterTable
ALTER TABLE "Player" ADD COLUMN     "photoOffsetX" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "photoOffsetY" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "photoZoom" DECIMAL(3,2) NOT NULL DEFAULT 1.0;

